### ISSUE TITLE
'Date completed' error for Araweté

### ISSUE THREAD

**Issue by rsprouse** [levmichael/saphon#34]
In processing the Araweté spreadsheet tab (index 4), the following error was generated:

```
Could not split line 'Date completed:': not enough values to unpack (expected 2, got 1)
```

**Comment by rsprouse** [comment]
@levmichael @mlapier 

Spreadsheet parsing requires that all fields have a value. In this case the 'Date completed' field in row 411 does not have one.

If an appropriate completion date is known it should be entered. If not, perhaps we could use a dummy placeholder value such as `TBD` or `TODO`. What would you like?

**Comment by czhao028** [comment]
Asuriní do Tocantins [asu] and Avá-Canoeiro (Tocantins) also have this error

**Comment by rsprouse** [comment]
Discussion 20240118: Stop tracking this field and suppress this warning message.

**Comment by rsprouse** [comment]
Warning message suppressed.
