### ISSUE TITLE
'not enough values to unpack (expected 2, got 1)' error for 'Asuriní do Tocantins'

### ISSUE THREAD

**Issue by czhao028** [levmichael/saphon#36]
This was caused by these cells (row 387-390):

> Couldn't access the following:
> Harrison, Carl H. Asurini morphophonology [s. loc.] University of Pensylvania, 1967. Tese submetida a exame para a obtenção do grau de Master of Arts. 70 fls. li No Arquivo do Setor de Linguística do Departamento de Antropologia do M.N. /U.F.R.J.
> HARRISON, Carl H. The phonemes of Asuriní, a language of Brazil. Brasília, S.I.L. [s.d.a] 14 fls. No Arquivo do Setor de Lingüística do Departamento de Antropologia do Museu Nacional/U.F.R.J.
> NICHOLSON, Velda. Ordem frasal de cláusulas na língua asurini. Brasília, S.I.L., 1977. Cópia datilografada constante do Arquivo do Setor de Lingüística do Departamento de Antropologia do Museu Nacional/U .F. R. J.

Resolution: Access the following sources to confirm analyses, and then delete these cells

**Comment by czhao028** [comment]
Related to additional errors, 

> Could not split line 'Date completed:': not enough values to unpack (expected 2, got 1)
> 
> Could not split line 'Notes:': not enough values to unpack (expected 2, got 1)
> 
> Proc {'undergoers': {}, 'triggers': [{}]} missing "proc_type" key
> 
> Proc {'undergoers': {}, 'triggers': [{}]} missing "proc_name" key
> 
> Proc {'undergoers': {}, 'triggers': [{}]} missing "proc_name" key
> 
> Proc {'undergoers': {}, 'triggers': [{}]} missing "transparencies", "opacities", or "undergoers" key
> 
> Proc {'undergoers': {}, 'triggers': [{}]} missing "transparencies", "opacities", or "undergoers" key

as well (rows 392-397) as those are empty.

Once the Nicholson source can be accessed and its analysis recorded, and those cells are populated, this issue will go away.

**Comment by rsprouse** [comment]
@levmichael @mlapier 

The resolution in the first cell is correct. What would you like to do with the misplaced content?

**Comment by rsprouse** [comment]
RESOLUTION: Move the contents of these lines to the `Notes` field of the `Synthesis` document.
