### ISSUE TITLE
Problem 'Cannot find identity phone [phoneName] in allophone list' for Chiriguano Ava

### ISSUE THREAD

**Issue by czhao028** [levmichael/saphon#37]
Errors:

> Cannot find identity phone i in allophone list ['ĩ'] for proc list ['LDNH', 'MPP=LDNH:Root']
> Problem parsing proc 'LDNH': 'NoneType' object has no attribute 'strip'
> Cannot find identity phone e in allophone list ['ẽ', 'ɛ̃'] for proc list ['ẽ-LDNH', 'MPP=ẽ-LDNH:Root', 'ɛ̃-LDNH', 'MPP=ɛ̃-LDNH:Root']
> Proc phone ẽ does not match allophone ɛ̃
> Cannot find identity phone ɨ in allophone list ['ɨ̃'] for proc list ['LDNH', 'MPP=LDNH:Root']
> Problem parsing proc 'LDNH': 'NoneType' object has no attribute 'strip'
> Cannot find identity phone a in allophone list ['ã', 'ɑ̃'] for proc list ['ã-LDNH', 'MPP=ã-LDNH:Root', 'ɑ̃-LDNH', 'MPP=ɑ̃-LDNH:Root']
> Proc phone ã does not match allophone ɑ̃
> Cannot find identity phone u in allophone list ['ũ'] for proc list ['LDNH', 'MPP=LDNH:Root']
> Problem parsing proc 'LDNH': 'NoneType' object has no attribute 'strip'
> Cannot find identity phone o in allophone list ['õ', 'ɔ̃'] for proc list ['õ-LDNH', 'MPP=õ-LDNH:Root', 'ɔ̃-LDNH', 'MPP=ɔ̃-LDNH:Root']
> Proc phone õ does not match allophone ɔ̃
> Cannot find identity phone w in allophone list ['β̃', 'w̃'] for proc list ['β̃-LDNH', 'MPP=β̃-LDNH:Root', 'w̃-LDNH', 'MPP=w̃-LDNH:Root']
> Proc phone β̃ does not match allophone w̃
> Cannot find identity phone ɾ in allophone list ['ɾ̃', 'n'] for proc list ['ɾ̃-LDNH', 'MPP=ɾ̃-LDNH:Root', 'n-LDNH', 'MPP=n-LDNH:Root']
> Proc phone ɾ̃ does not match allophone n

Solution:
For each of these examples, we just need to insert the basic allophone into the list of allophones alongside its derived allophones. For example,
`{i, ĩ, &, {LDNH, MPP=LDNH:Root}}, {e, {ẽ, ɛ̃}, &, {ẽ-LDNH, MPP=ẽ-LDNH:Root, ɛ̃-LDNH, MPP=ɛ̃-LDNH:Root}}`
should be
`{i, {i, ĩ}, &, {LDNH, MPP=LDNH:Root}}, {e, {e, ẽ, ɛ̃}, &, {ẽ-LDNH, MPP=ẽ-LDNH:Root, ɛ̃-LDNH, MPP=ɛ̃-LDNH:Root}}`

**Comment by rsprouse** [comment]
@levmichael @mlapier 

@czhao028's solution looks correct to me. How would you like these to be handled?

**Comment by czhao028** [comment]
@mlapier suggested to prefix with ĩ (so process list is [' ĩ-LDNH', 'MPP=LDNH:Root']), but this solution did not work. Solution still undetermined.

**Comment by rsprouse** [comment]
After recent updates these errors no longer appear.
