### ISSUE TITLE
Problem 'value not in Natural Classes/Segments/Morpheme IDs' for Chiriguano Ava

### ISSUE THREAD

**Issue by czhao028** [levmichael/saphon#38]
Errors below. For example, in '//V//' (b'//V//'), the incorrectly detected value is //V// in the spreadsheet (the right-hand side is the value in bytes):

1. undergoers value '//V//' (b'//V//') not in Natural Classes/Segments/Morpheme IDs 'p, t, k, kʷ, s, tʃ, //M//, //N//, //Ŋ//, //J//, ɾ, w, i, e, ɨ, a, u, o, ĩ, ẽ, ɨ̃, ã, ũ, õ, ɲo, ra, ramo, rani, ma, téi, tei, T, S, //NN//, R, V, Ṽ' for Dietrich, Wolf. 1986. El idioma chiriguano: gramática, textos, vocabulario. Madrid: Instituto de Cooperación Iberoamericana. (ava)
2. opacities value 'ˈV' (b'\xcb\x88V') not in Natural Classes/Segments/Morpheme IDs 'p, t, k, kʷ, s, tʃ, //M//, //N//, //Ŋ//, //J//, ɾ, w, i, e, ɨ, a, u, o, ĩ, ẽ, ɨ̃, ã, ũ, õ, ɲo, ra, ramo, rani, ma, téi, tei, T, S, //NN//, R, V, Ṽ' for Dietrich, Wolf. 1986. El idioma chiriguano: gramática, textos, vocabulario. Madrid: Instituto de Cooperación Iberoamericana. (ava)
3. opacities value 'ˌV' (b'\xcb\x8cV') not in Natural Classes/Segments/Morpheme IDs 'p, t, k, kʷ, s, tʃ, //M//, //N//, //Ŋ//, //J//, ɾ, w, i, e, ɨ, a, u, o, ĩ, ẽ, ɨ̃, ã, ũ, õ, ɲo, ra, ramo, rani, ma, téi, tei, T, S, //NN//, R, V, Ṽ' for Dietrich, Wolf. 1986. El idioma chiriguano: gramática, textos, vocabulario. Madrid: Instituto de Cooperación Iberoamericana. (ava)
4. undergoers value 'r' (b'r') not in Natural Classes/Segments/Morpheme IDs 'p, t, k, kʷ, s, tʃ, //M//, //N//, //Ŋ//, //J//, ɾ, w, i, e, ɨ, a, u, o, ĩ, ẽ, ɨ̃, ã, ũ, õ, ɲo, ra, ramo, rani, ma, téi, tei, T, S, //NN//, R, V, Ṽ' for Dietrich, Wolf. 1986. El idioma chiriguano: gramática, textos, vocabulario. Madrid: Instituto de Cooperación Iberoamericana. (ava)
5. opacities value 'ˈV' (b'\xcb\x88V') not in Natural Classes/Segments/Morpheme IDs 'p, t, k, kʷ, s, tʃ, //M//, //N//, //Ŋ//, //J//, ɾ, w, i, e, ɨ, a, u, o, ĩ, ẽ, ɨ̃, ã, ũ, õ, ɲo, ra, ramo, rani, ma, téi, tei, T, S, //NN//, R, V, Ṽ' for Dietrich, Wolf. 1986. El idioma chiriguano: gramática, textos, vocabulario. Madrid: Instituto de Cooperación Iberoamericana. (ava)
6. opacities value 'ˌV' (b'\xcb\x8cV') not in Natural Classes/Segments/Morpheme IDs 'p, t, k, kʷ, s, tʃ, //M//, //N//, //Ŋ//, //J//, ɾ, w, i, e, ɨ, a, u, o, ĩ, ẽ, ɨ̃, ã, ũ, õ, ɲo, ra, ramo, rani, ma, téi, tei, T, S, //NN//, R, V, Ṽ' for Dietrich, Wolf. 1986. El idioma chiriguano: gramática, textos, vocabulario. Madrid: Instituto de Cooperación Iberoamericana. (ava)

**Comment by rsprouse** [comment]
@levmichael @mlapier 

Note that these errors are from reference section `Dietrich, Wolf 1986`. Does this indicate Jiacheng should resolve them?

The solution will require determining the status of the symbols `//V//`, `ˈV`, `ˌV`, `r` in this source.

**Comment by rsprouse** [comment]
RESOLUTION: Assign this to Jiacheng when he is added to the repository.

**Comment by rsprouse** [comment]
Disregard the last comment, which is relevant to a different issue #39.
