### ISSUE TITLE
'Could not split line 'Notes:'' for [Guarayu, Paraguayan Guaraní, Siriono]

### ISSUE THREAD

**Issue by michael-pollack** [levmichael/saphon#45]
Guarayu, rng=[17]

```
Could not split line 'Notes:': not enough values to unpack (expected 2, got 1)
```

**Comment by michael-pollack** [comment]
Paraguayan Guaraní, rng=[43]

`Could not split line 'Notes:': not enough values to unpack (expected 2, got 1)`

**Comment by michael-pollack** [comment]
Siriono, rng=[49]

`Could not split line 'Notes:': not enough values to unpack (expected 2, got 1)`

**Comment by rsprouse** [comment]
@levmichael @mlapier 

We need to add an explicit empty placeholder for the `Notes` field. Use `NA`?

**Comment by rsprouse** [comment]
RESOLUTION: When the `Notes` field has no value, use `empty`.
