### ISSUE TITLE
'Character not in IPA table' for Mbyá (Mbyá do Brasil)

### ISSUE THREAD

**Issue by michael-pollack** [levmichael/saphon#54]
Mbyá (Mbyá do Brasil), rng=[33]

```
Character ∅ (b'\xe2\x88\x85') is not in ipa-table.txt.

Character ∅ (b'\xe2\x88\x85') is not in ipa-table.txt.
```

**Comment by rsprouse** [comment]
@levmichael @mlapier 

Do you want to add `∅` to the list of allowed symbols in `ipa-table.txt`?

**Comment by rsprouse** [comment]
This symbol appears in line 358, `Natural Classes` within the string `{S, {h, ∅}}`.

**Comment by rsprouse** [comment]
RESOLUTION: Do not add `∅` as a symbol in `ipa-table.txt`.

Myriam has changed this string to `{S, h}`.
