### ISSUE TITLE
ERROR: spreadsheet tab Cinta Larga failed. No synthesis found. (Cinta Larga)

### ISSUE THREAD

**Issue by czhao028** [levmichael/saphon#63]
Unlike other spreadsheet tabs, Cinta Larga (12) does not have a synthesis section.

**Comment by rsprouse** [comment]
RESOLUTION: We do not regard this as a `spreadsheet_parse` error per se since it indicates that work on this language has not yet occurred. You can just ignore it for now and skip processing this language tab.
