### ISSUE TITLE
Error: encountered extraneous closing quote at pos 317 (Kaiwá)

### ISSUE THREAD

**Issue by czhao028** [levmichael/saphon#65]
Related error messages:

> Error in allophone list {{p, mb, mbo-_, MPP=LNsyll:mbo}, {s, nd, mbo-_, MPP=LNsyll:mbo}, {k, ŋg, mbo-_, MPP=LNsyll:mbo}, {h, nd, mbo-_, MPP=LNsyll:mbo}, {dʲ, ɲ, &, MPP=LDNH:prefixes}, {nd, n, &, MPP=LDNH:prefixes}, {mb, m, &, MPP=LDNH:prefixes}, {p, mb, &, MPP=LN:pa}, {ɾ, n, &, MPP=LDNH:prefixes}, {∅, h, /V+ʔ/, hV+ʔ, consonant epenthesis}, }. 'n, s, p, e, c, i, f, i, e, d' for Taylor, John. M. & Audrey H. Taylor. 2010. Statement of Kaiwá Grammar from Clause to Morpheme Level. SIL Brasil.
> encountered extraneous closing quote at pos 317: '}'
> 
> Process name MPP=LNsyll:mbo not used by any allophones  for Taylor, John. M. & Audrey H. Taylor. 2010. Statement of Kaiwá Grammar from Clause to Morpheme Level. SIL Brasil.
> 
> Process name MPP=LDNH:prefixes not used by any allophones  for Taylor, John. M. & Audrey H. Taylor. 2010. Statement of Kaiwá Grammar from Clause to Morpheme Level. SIL Brasil

Solution: remove the extra comma at the end of `**...consonant epenthesis}, }**` in row 84 on tab 22. Thus, becomes `**...consonant epenthesis}}**`.

Tested solution locally using `used_cached=True` and removed all the error messages above.

**Comment by mlapier** [comment]
RESOLVED: Removed the relevant comma, as suggested
