### ISSUE TITLE
ERROR: spreadsheet tab failed - KeyError: 'notes' (Kaiowá)

### ISSUE THREAD

**Issue by czhao028** [levmichael/saphon#66]
There is no "Notes" section in the synthesis portion of Kaiowá (tab 22). In the meeting on 1/18, we discussed using a substitute value for "Date completed" to make that field optional.

**Possible A/I: make Notes section optional?**

**Comment by rsprouse** [comment]
RESOLUTION: Since our earlier solution just interpolates an empty value (add the Notes line by hand with the value 'None'), let's just do this interpolation in the code instead.

- [ ] Update spreadsheet parse to use 'None' as the value for 'Notes' when 'Notes' is missing.

**Comment by rsprouse** [comment]
See also #56.

**Comment by rsprouse** [comment]
The `notes` field is now handled gracefully when missing from the spreadsheet.
